### PR TITLE
Fix reference to VersionMismatchError after namespace change

### LINKED ISSUE #664: HEAD and most of the latest releases are broken, references an undefined exception
image

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
# Bug fix

## Description

This reference to `StimulusReflex::Reflex::VersionMismatchError` in `StimulusReflex::Channel` is using an old namespace that was changed recently to `StimulusReflex::VersionMismatchError`.

## Why should this be added

Fixes #664 reported by @obie, additional discussion here: https://discord.com/channels/629472241427415060/733725826411135107/1113306088796864615

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing

### CODE REVIEW

File: app/channels/stimulus_reflex/channel.rb [hunk 1]
```diff
@@ -1,5 +1,7 @@
 # frozen_string_literal: true
 
+require "stimulus_reflex/version_checker"
+
```
Comment (marcoroth) [inline app/channels/stimulus_reflex/channel.rb:4]: I don't think this is needed.
```suggestion
```

**Review by marcoroth — COMMENTED** [review]
Thank you for promptly fixing this, @Matt-Yorkley!

**Review by marcoroth — APPROVED** [review]
Thank you!
